apiVersion: v3
appVersion: 1.0.0-beta5
description: A Prometheus exporter for MongoDB custom query/aggregations
home: https://github.com/raffis/mongodb-query-exporter
keywords:
- exporter
- metrics
- mongodb
- query-
- aggregation
- prometheus
name: prometheus-mongodb-query-exporter
sources:
- https://github.com/raffis/mongodb-query-exporter
version: 1.0.0
