apiVersion: v2
appVersion: 2.0.3
description: A Prometheus exporter for MongoDB custom aggregations
home: https://github.com/raffis/mongodb-query-exporter
maintainers:
- name: raffis
  email: raffael.sahli@gmail.com
keywords:
- exporter
- metrics
- mongodb
- aggregation
- query
- prometheus
name: mongodb-query-exporter
sources:
- https://github.com/raffis/mongodb-query-exporter
version: 4.0.1
