apiVersion: v2
appVersion: v1.0.0
description: A Prometheus exporter for MongoDB custom aggregations
home: https://github.com/raffis/mongodb-query-exporter
maintainers:
- name: raffis
  email: raffael.sahli@gmail.com
keywords:
- exporter
- metrics
- mongodb
- aggregation
- query
- prometheus
name: prometheus-mongodb-query-exporter
sources:
- https://github.com/raffis/mongodb-query-exporter
version: 2.1.0
